name: 腾讯云CDN刷新缓存
on:
  workflow_run:
    workflows: ["GitHub pages"]
    types:
      - completed

jobs:
  deploy-to-qcloud-cdn:
    name: Tencent Cloud CDN Purge Cache
    runs-on: ubuntu-latest
    steps:
      - name: 刷新缓存
        uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
        env:
          SECRET_ID: ${{ secrets.QCLOUD_SECRET_ID}}
          SECRET_KEY: ${{ secrets.QCLOUD_SECRET_KEY }}
          PATHS: "https://docs.vlssu.com/"
          FLUSH_TYPE: "flush" # optional
