name: 腾讯云CDN刷新缓存和SSL
on: push
jobs:
  deploy-to-qcloud-cdn:
    name: Deploy certificate to Tencent Cloud CDN
    runs-on: ubuntu-latest
    steps:
      - name: 刷新缓存
        uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
        env:
          SECRET_ID: ${{ secrets.QCLOUD_SECRET_ID}}
          SECRET_KEY: ${{ secrets.QCLOUD_SECRET_KEY }}
          PATHS: "https://docs.vlssu.com/"
          FLUSH_TYPE: "flush" # optional
      - name: Check out
        uses: actions/checkout@v2
        with:
          # If you just commited and pushed your newly issued certificate to this repo in a previous job,
          # use `ref` to make sure checking out the newest commit in this job
          ref: ${{ github.ref }}
      - uses: renbaoshuo/deploy-certificate-to-tencentcloud@beta-v1
        with:
          # Use Access Key
          secret-id: ${{ secrets.QCLOUD_SECRET_ID }}
          secret-key: ${{ secrets.QCLOUD_SECRET_KEY }}

          # Specify PEM fullchain file
          fullchain-file: ${{ env.FILE_FULLCHAIN }}
          # Specify PEM private key file
          key-file: ${{ env.FILE_KEY }}

          # Deploy to CDN
          cdn-domains: |
            docs.vlssu.com
